### ISSUE TITLE
Inform the user before invoking download_project

### ISSUE THREAD

**Issue by awvwgk** [qcscine/cmake#1]
It seems like a normal CMake build for a project using this configuration files can silently pull in new software stacks. After inspecting the `ImportGTest.cmake` it looks like there will be a message _after_ the transaction is _finished_, while this is a valid strategy it is certainly more transparent to inform the user _before_ starting a transaction to pull in third-party dependencies.

In my case I would have preferred to actually get the option to install those dependencies via my systems package manager rather than automatically downloading them, which would require to know that they are dependencies in the first place. Currently this seems to require reading through all the CMake files in this repository to determine the necessary third-party dependencies.

**Comment by nabbelbabbel** [comment]
Thanks for the feedback.

> In my case I would have preferred to actually get the option to install those dependencies via my systems package manager rather than automatically downloading them, which would require to know that they are dependencies in the first place. Currently this seems to require reading through all the CMake files in this repository to determine the necessary third-party dependencies.

Sure, it should be possible and preferred to use existing installations of required libraries this is discussed in #2 . 

The knowledge of the required libraries boils down to documentation, at the moment we only list the dependencies for the actually installed targets. The tests are not installed and thus the dependencies are not listed. As a trade off we did not expect them to be magically present but cache the in the build folder for you. We will reconsider this for the next release as it will have many quality of life changes for the install process of SCINE. 

> ... it looks like there will be a message after the transaction is finished, ...

Indeed that message should be printed before the download. It should be a simple fix we will add to our list for the next release and keep this issue open until then.

**Comment by weymutht** [comment]
This has been fixed with release 4.0.0 of development-utils. Therefore, I close this issue.
